### ISSUE TITLE
Need examples/demos for using Kinect in C#

### ISSUE THREAD

**Issue by paranoiacblack** [arellanj/XNA_Tetris#1]
So, after our discussion earlier, I think we just need some momentum via stealing someone's ideas. I'll try to keep updating this issue with relevant ideas. So far, I found this project which, alongside Pong, provides a few other Kinect projects and examples: https://github.com/atosorigin/Kinect. Oh, also, it teaches bros how to use dat Github.

**Comment by arellanj** [comment]
The above still use the old version of the Kinect SDK. I tried compiling it and 4 of them failed. Im pretty sure we can still use it for the demos, and maybe if we change some stuff around we can compile them. Also, I found this http://kinectxna.blogspot.com/ <-this, it only a few tutorials but its a start.

**Comment by paranoiacblack** [comment]
There's a lot of people that develop for the Kinect. We have to be missing something obvious here.
